# Jack Rabbit Tests Makefile
# jsp Fri Feb  6 17:17:03 CST 2009

CCFILES=$(shell ls -1 *.cc)
TARGETS=$(basename $(CCFILES))
INCLUDEPATH=.. ../../horny_toad
DEPENDPATH=.. ../../horny_toad
EXTRA_SOURCES=
LIBS=-lfftw3

include ../../Makefile.tests
